name: UCAI Core Tests

on:
  push:
    branches:
      - main
    paths:
      - ai/**
      - .github/workflows/ucai-*.yml
  pull_request:
    paths:
      - ai/**
      - .github/workflows/ucai-*.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ai
    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.9'
      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4.2.0
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: uv sync --group lint
      - name: Activate virtual environment
        run: |
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/ai/.venv" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/ai/.venv/bin" >> $GITHUB_PATH
      - name: Lint Python code with ruff
        run: uv run --no-sync ruff check .
      - name: Lint Python code format with ruff
        run: uv run --no-sync ruff format --check .
      - name: Lint YAML files with yamllint
        run: uv run --no-sync yamllint .

  core_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']
        pydantic-version: [1, 2]
    timeout-minutes: 40
    defaults:
      run:
        working-directory: ai
    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Set up JDK 17
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --group core-tests
      - name: Activate virtual environment
        run: |
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/ai/.venv" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/ai/.venv/bin" >> $GITHUB_PATH
      - name: Install Pydantic version for matrix testing
        run: |
          if [ ${{ matrix.pydantic-version }} == 1 ]; then
            uv pip install 'pydantic<2'
          else
            uv pip install 'pydantic<3,>=2'
          fi
      - name: Install Unity Catalog Python Libraries
        run: |
          dev/install_client.sh
      - name: Start Unity Catalog Server
        run: |
          dev/start_unitycatalog.sh
      - name: Run Tests
        run: |
          uv run --no-sync pytest core/tests --ignore=core/tests/core/databricks/test_databricks_unit_tests.py
      - name: Run Databricks Unit Tests
        if: matrix.python-version == '3.10'
        run: |
          uv run --no-sync pytest core/tests/core/databricks/test_databricks_unit_tests.py
      - name: Stop Unity Catalog Server
        if: always()
        run: |
          dev/teardown_server.sh
